[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/scan/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/manager"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/manager/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
